# Generated by Django 4.0.4 on 2022-04-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_image', models.ImageField(blank='True', null='True', upload_to='categorypics')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=50)),
                ('subcategory_image', models.ImageField(blank='True', null='True', upload_to='subcategorypics')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('discount_percent', models.IntegerField(default=0)),
                ('Image1', models.ImageField(blank='True', null='True', upload_to='productpics')),
                ('Image2', models.ImageField(blank='True', null='True', upload_to='productpics')),
                ('Image3', models.ImageField(blank='True', null='True', upload_to='productpics')),
                ('featured_product', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.subcategory')),
            ],
        ),
    ]
